export const PERMISSIONS = {
  CATALOG_PRODUCT_MANAGE: 'catalog.product.manage',
  IDENTITY_USER_MANAGE: 'identity.user.manage',
  INVENTORY_MATERIAL_MANAGE: 'inventory.material.manage',
  INVENTORY_LOCATION_MANAGE: 'inventory.location.manage',
  INVENTORY_UNIT_MANAGE: 'inventory.unit.manage',
  INVENTORY_WAREHOUSE_MANAGE: 'inventory.warehouse.manage',
  INVENTORY_MOVEMENT_CREATE: 'inventory.movement.create',
  INVENTORY_ADJUSTMENT_CREATE: 'inventory.adjustment.create',
  PROCUREMENT_SUPPLIER_MANAGE: 'procurement.supplier.manage',
  PROCUREMENT_ORDER_MANAGE: 'procurement.order.manage',
  PROCUREMENT_ORDER_RECEIVE: 'procurement.order.receive',
  PROCUREMENT_REQUISITION_MANAGE: 'procurement.requisition.manage',
  APPROVAL_DECIDE: 'approval.decide',
  PRODUCTION_RECIPE_MANAGE: 'production.recipe.manage',
  PRODUCTION_ORDER_CREATE: 'production.order.create',
  PRODUCTION_ORDER_RELEASE: 'production.order.release',
  PRODUCTION_ORDER_START: 'production.order.start',
  PRODUCTION_ORDER_CANCEL: 'production.order.cancel',
  PRODUCTION_ORDER_COMPLETE: 'production.order.complete',
  PRODUCTION_COST_CALCULATE: 'production.cost.calculate',
  PRODUCTION_LOT_RELEASE: 'production.lot.release',
  QUALITY_INSPECTION_MANAGE: 'quality.inspection.manage',
  QUALITY_RELEASE_DECIDE: 'quality.release.decide',
  SALES_ORDER_CREATE: 'sales.order.create',
  SALES_ORDER_CONFIRM: 'sales.order.confirm',
  SALES_ORDER_PREPARE: 'sales.order.prepare',
  SALES_ORDER_DELIVER: 'sales.order.deliver',
  SALES_ORDER_PROFIT_CALCULATE: 'sales.order.profit.calculate',
  SALES_CUSTOMER_MANAGE: 'sales.customer.manage',
  SALES_QUOTE_MANAGE: 'sales.quote.manage',
  FINANCE_INVOICE_MANAGE: 'finance.invoice.manage',
  FINANCE_RECEIVABLE_MANAGE: 'finance.receivable.manage',
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
